import CreateListingForm from "@/components/modules/Listings/CreateListingForm";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "BashaFinder || house-listing",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div className=" pt-40 pb-20">
      <CreateListingForm />
    </div>
  );
};

export default page;
